# Generated by Django 5.1.3 on 2024-11-20 07:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('not_started', '未着手'), ('start', '着手'), ('completed', '完了')], default='not_started', max_length=30)),
            ],
        ),
    ]
