# Generated by Django 5.1.3 on 2024-11-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoMoodel',
            new_name='TodoModel',
        ),
    ]
