# Generated by Django 5.1.3 on 2024-11-19 01:24

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_todomoodel_todomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='status',
            field=model_utils.fields.StatusField(choices=[('not_started', 'not_started'), ('start', 'start'), ('completed', 'completed')], default='not_started', max_length=100, no_check_for_status=True),
        ),
    ]
