# Generated by Django 5.1.3 on 2024-11-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todomodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='status',
            field=models.CharField(choices=[('not_started', '未着手'), ('start', '着手'), ('completed', '完了')], default='not_started', max_length=30),
        ),
    ]
